export const bunsWorldRankingPoll = {
  slug: "buns-world-ranking",
  headline: "WHERE ARE YOU FROM?",
  subheadline: "Vote and put your country on the BUNS world ranking.",
  pollQuestion: "Which country are you from?",
  pollOptions: [
    "Portugal",
    "Germany",
    "France",
    "United Kingdom",
    "Netherlands",
    "Spain",
    "Italy",
    "United States",
    "Brazil",
    "Ireland",
    "Belgium",
    "Sweden",
    "Denmark",
    "Australia",
    "Other",
  ],
} as const;

export const bunsWorldRankingScreenCampaign = {
  type: "poll_results",
  campaign_id: "buns-world-ranking",
  poll_id: "buns-world-ranking",
  linked_landing_slug: "buns-world-ranking",
  linked_landing_url: "/lp/buns-world-ranking",
  headline: "WHERE ARE YOU FROM?",
  subheadline: "Vote and put your country on the BUNS world ranking.",
  cta: "Scan to vote",
  qr_label: "Scan to represent your country",
  qr_cta: "Open world ranking",
  poll_question: "Which country are you from?",
  poll_options: [...bunsWorldRankingPoll.pollOptions],
  season_label: "Season live",
} as const;
